version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql:8
  restart: unless-stopped
  environment:
   MYSQL_DATABASE: tpstock
   MYSQL_ROOT_PASSWORD: root
  volumes:
   - /home/vagrant/mysqldata:/var/lib/mysql
    
 spring_app:
  image: medamine1212/achat-1.0-s7:latest
  container_name: tpachat
  restart: on-failure
  ports:
   - 9090:9090
  depends_on:
   - mysqldb
