version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql:8
  restart: unless-stopped
  environment:
   MYSQL_DATABASE: tpachato
   MYSQL_ROOT_PASSWORD: root
  volumes:
   - /home/vagrant/mysqldata:/var/lib/mysql
    
 spring_app:
  image: tpachat-1.0
  container_name: tpachat
  restart: on-failure
  ports:
   - 9091:9091
  depends_on:
   - mysqldb
